### ISSUE TITLE
How configure Redis Sentinel 

### ISSUE THREAD

**Issue by Yozhef** [symfony-bundles/redis-bundle#19]
Can you tell me how to configure the Redis Sentinel correctly?
My setting:
sb_redis.yaml
```
sb_redis:
    clients:
        default:
            $options:    []
            $parameters: ['%env(REDIS_URL)%']
or

sb_redis:
    clients:
        default:
            $options: [replication : sentinel, service : platform-common-develop]
            $parameters: ['%env(REDIS_SENTINEL_URL)%']
```
.env
```
REDIS_URL=redis://main-develop-redis:26379?redis_sentinel=platform-main-develop&dbindex=0&replication=sentinel&service=platform-main-develop&database=0
```
But a have exeption:
```
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "status": 500,
    "detail": "`SELECT` failed: ERR unknown command `SELECT`, with args beginning with: `0`,  [redis://platform-main-develop-redis:26379]",
    "class": "Predis\\Connection\\ConnectionException",

```

**Comment by khaperets** [comment]
Hi, Yozhef!
See issue https://github.com/nrk/predis/issues/355, I hope this helps you.

**Comment by Yozhef** [comment]
@khaperets Sorry but that didn't help me with the problem. I don't understand how to properly transfer configurations from Symfony-bundle to Predis Client. Do you have any idea?

**Comment by moskitone** [comment]
Hi @khaperets.

Does redis sentinel supported?
Due to predis documentation there has to be field $sentinels and no $parameters

```
$sentinels = ['tcp://10.0.0.1', 'tcp://10.0.0.2', 'tcp://10.0.0.3'];
$options   = ['replication' => 'sentinel', 'service' => 'mymaster'];

$client = new Predis\Client($sentinels, $options);
```

**Comment by Yozhef** [comment]
Thank you all worked it was necessary to add 2 parameters correctly.
```
sb_redis:
    clients:
        default:
            $options:
                replication: sentinel
                service: platform-common-develop
                parameters:
                    database: 0
            $parameters: ['%env(REDIS_URL)%', '%env(REDIS_URL)%']
```
